"""create_all_tables

Revision ID: 7011ef78763b
Revises: 
Create Date: 2026-04-13 20:33:34.658056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7011ef78763b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('producto',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('categoria', sa.Enum('alimento', 'quimico', 'veterinario', 'equipo', 'repuesto', 'general', name='categoria_producto'), nullable=False),
    sa.Column('codigo_barras', sa.String(length=50), nullable=True),
    sa.Column('unidad_medida', sa.String(length=20), nullable=False),
    sa.Column('temperatura_requerida', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('stock_minimo', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('descripcion', sa.String(length=300), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sede',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.Enum('ponton', 'planta', 'bodega', name='tipo_sede'), nullable=False),
    sa.Column('ubicacion', sa.String(length=200), nullable=True),
    sa.Column('latitud', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitud', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('capacidad_total', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Enum('activo', 'inactivo', name='estado_sede'), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('galpon',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('id_sede', sa.String(length=36), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('filas', sa.Integer(), nullable=False),
    sa.Column('columnas', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('activo', 'inactivo', name='estado_galpon'), nullable=True),
    sa.ForeignKeyConstraint(['id_sede'], ['sede.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rut', sa.String(length=12), nullable=True),
    sa.Column('codigo_empleado', sa.String(length=20), nullable=False),
    sa.Column('rol', sa.Enum('super_admin', 'admin_sede', 'jefe_bodega', 'operario', 'gerencia', name='rol_usuario'), nullable=False),
    sa.Column('id_sede', sa.String(length=36), nullable=True),
    sa.Column('turno', sa.Enum('A', 'B', name='turno_usuario'), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('ultimo_acceso', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_sede'], ['sede.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_empleado'),
    sa.UniqueConstraint('email')
    )
    op.create_table('container',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('id_galpon', sa.String(length=36), nullable=False),
    sa.Column('codigo', sa.String(length=15), nullable=False),
    sa.Column('posicion_fila', sa.Integer(), nullable=False),
    sa.Column('posicion_col', sa.Integer(), nullable=False),
    sa.Column('capacidad_max', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unidad_medida', sa.String(length=20), nullable=False),
    sa.Column('ocupacion_actual', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('estado', sa.Enum('disponible', 'medio', 'critico', 'mantenimiento', 'cuarentena', name='estado_container'), nullable=True),
    sa.Column('tipo_producto_permitido', sa.Enum('alimento', 'quimico', 'veterinario', 'equipo', 'repuesto', 'general', name='tipo_producto_container'), nullable=True),
    sa.Column('temperatura_requerida', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('motivo_estado', sa.String(length=200), nullable=True),
    sa.Column('ultimo_movimiento', sa.DateTime(timezone=True), nullable=True),
    sa.Column('qr_code', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['id_galpon'], ['galpon.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario_galpon',
    sa.Column('id_usuario', sa.String(length=36), nullable=False),
    sa.Column('id_galpon', sa.String(length=36), nullable=False),
    sa.Column('fecha_asignacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_galpon'], ['galpon.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id_usuario', 'id_galpon')
    )
    op.create_table('alerta',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('id_container', sa.String(length=36), nullable=False),
    sa.Column('id_usuario_revision', sa.String(length=36), nullable=True),
    sa.Column('tipo', sa.Enum('capacidad_critica', 'vencimiento_30_dias', 'vencimiento_7_dias', 'stock_minimo', 'movimiento_fuera_horario', 'discrepancia_inventario', 'sin_movimiento_30_dias', 'cuarentena_activa', name='tipo_alerta'), nullable=False),
    sa.Column('severidad', sa.Enum('critica', 'aviso', 'informativa', name='severidad_alerta'), nullable=False),
    sa.Column('descripcion', sa.String(length=300), nullable=False),
    sa.Column('estado', sa.Enum('activa', 'revisada', 'resuelta', name='estado_alerta'), nullable=True),
    sa.Column('fecha_generacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_revision', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_container'], ['container.id'], ),
    sa.ForeignKeyConstraint(['id_usuario_revision'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movimiento',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('id_container', sa.String(length=36), nullable=False),
    sa.Column('id_container_destino', sa.String(length=36), nullable=True),
    sa.Column('id_usuario', sa.String(length=36), nullable=False),
    sa.Column('id_usuario_aprobador', sa.String(length=36), nullable=True),
    sa.Column('id_producto', sa.String(length=36), nullable=False),
    sa.Column('id_movimiento_original', sa.String(length=36), nullable=True),
    sa.Column('tipo', sa.Enum('entrada_proveedor', 'salida_produccion', 'traslado_interno', 'correccion', name='tipo_movimiento'), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'aprobado', 'rechazado', name='estado_movimiento'), nullable=True),
    sa.Column('cantidad', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('numero_lote', sa.String(length=50), nullable=False),
    sa.Column('fecha_fabricacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_vencimiento', sa.DateTime(timezone=True), nullable=False),
    sa.Column('nombre_proveedor', sa.String(length=150), nullable=True),
    sa.Column('rut_proveedor', sa.String(length=12), nullable=True),
    sa.Column('num_guia_despacho', sa.String(length=50), nullable=True),
    sa.Column('registro_sanitario', sa.String(length=50), nullable=True),
    sa.Column('temperatura_almacen', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('num_receta_retenida', sa.String(length=50), nullable=True),
    sa.Column('num_autorizacion_sag', sa.String(length=50), nullable=True),
    sa.Column('fecha_hora', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_aprobacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('motivo_rechazo', sa.String(length=300), nullable=True),
    sa.Column('observaciones', sa.String(length=300), nullable=True),
    sa.Column('origen', sa.Enum('online', 'offline_sync', name='origen_movimiento'), nullable=True),
    sa.Column('flag_fefo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_container'], ['container.id'], ),
    sa.ForeignKeyConstraint(['id_container_destino'], ['container.id'], ),
    sa.ForeignKeyConstraint(['id_movimiento_original'], ['movimiento.id'], ),
    sa.ForeignKeyConstraint(['id_producto'], ['producto.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['id_usuario_aprobador'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movimiento')
    op.drop_table('alerta')
    op.drop_table('usuario_galpon')
    op.drop_table('container')
    op.drop_table('usuario')
    op.drop_table('galpon')
    op.drop_table('sede')
    op.drop_table('producto')
    # ### end Alembic commands ###
