"""auth_security

Revision ID: d367941070ea
Revises: fbf2a21dfc87
Create Date: 2026-04-19 19:00:25.596267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd367941070ea'
down_revision: Union[str, Sequence[str], None] = 'fbf2a21dfc87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('intentos_fallidos', sa.Integer(), nullable=True))
    op.add_column('usuario', sa.Column('bloqueo_hasta', sa.DateTime(timezone=True), nullable=True))
    op.add_column('usuario', sa.Column('reset_token', sa.String(length=255), nullable=True))
    op.add_column('usuario', sa.Column('reset_token_expire', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'reset_token_expire')
    op.drop_column('usuario', 'reset_token')
    op.drop_column('usuario', 'bloqueo_hasta')
    op.drop_column('usuario', 'intentos_fallidos')
    # ### end Alembic commands ###
