"""add_log_auditoria

Revision ID: fbf2a21dfc87
Revises: 777a62cf61fb
Create Date: 2026-04-19 18:51:09.624062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbf2a21dfc87'
down_revision: Union[str, Sequence[str], None] = '777a62cf61fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_auditoria',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('id_usuario', sa.String(), nullable=False),
    sa.Column('accion', sa.String(), nullable=False),
    sa.Column('entidad_afectada', sa.String(), nullable=False),
    sa.Column('id_entidad', sa.String(), nullable=False),
    sa.Column('detalles', sa.JSON(), nullable=True),
    sa.Column('fecha_hora', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_auditoria_fecha_hora'), 'log_auditoria', ['fecha_hora'], unique=False)
    op.create_index(op.f('ix_log_auditoria_id_entidad'), 'log_auditoria', ['id_entidad'], unique=False)
    op.create_index(op.f('ix_log_auditoria_id_usuario'), 'log_auditoria', ['id_usuario'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_log_auditoria_id_usuario'), table_name='log_auditoria')
    op.drop_index(op.f('ix_log_auditoria_id_entidad'), table_name='log_auditoria')
    op.drop_index(op.f('ix_log_auditoria_fecha_hora'), table_name='log_auditoria')
    op.drop_table('log_auditoria')
    # ### end Alembic commands ###
